### ISSUE TITLE
Please add a license. Preferably an open source license.

### ISSUE THREAD

**Issue by vexorian** [DEFENDORe/pseudotv#101]
https://www.quora.com/What-if-I-dont-include-a-license-in-my-public-GitHub-project-Can-people-do-anything-with-my-code

`
By default creating a new project on Github that is public and without any explicit license terms falls under the "All rights reserved" category.
`

So there are a lot of issues here. Because this software wasn't released with a license. Since all rights are reserved, it means that users are not even legally allowed to run pseudotv in their servers. And all the people who have contributed code additions (and thus had to download the code to their computers) have done so without permission. And yes, this means that the dizqueTV fork's legality is also in question.

So I am paging @DEFENDORe  , it is REALLY IMPORTANT that this project gets released under a license. Otherwise all development and usage is in a legal limbo. And I will have to shut down all development of dizquetv and not be able to release it until I do a complete code rewrite. I am sorry I did so much stuff for a project and didn't check first to see if it actually had a license. I unfortunately just made assumptions based on seeing the project released in github and gitlab.

**Comment by vexorian** [comment]
Thank you, and thank you for the great work in pseudotv.

**Comment by DEFENDORe** [comment]
No problem. Keep up the great work with dizquetv! Im hoping over the next few months I can get back to working on the project again. Its just been a very busy year for me. Glad to see somebody taking charge and making some solid progress. Cheers, Dan.
