### ISSUE TITLE
Previous Channel option after switching channels in EPG Guide - enhancement request?

### ISSUE THREAD

**Issue by thepcnerdonline** [DEFENDORe/pseudotv#13]
Feature Request - After going to a channel from a previous channel in the EPG it would be nice if there was an option (FireTV "hamburger" button on Remote etc) to return to the previous channel without needing to open the guide and find it again. Currently on FireTV the down option does offer recently viewed channels but thought I would ask.

**Comment by FangsMcWolf** [comment]
Wouldn't that be something that would have to be handled on the Plex side?

**Comment by thepcnerdonline** [comment]
Thats truly possible... I do know that Lunatixz "PseudoTV Live" has random functions that do some things that aren't necessarily plex but again I am not sure. Feel free to delete or close if this is a silly request. Just finding little nuances as I use Pseudo that make me think... "hmmm... would be nice if this could..." but not super important. Thanks Wolfie.

**Comment by powdermilkman** [comment]
Yeah, this is only doable on Plex's end, we have no control of how the EPG works. Closing as wontfix as it's impossible as far as I can see. Thanks for your suggestion though!

**Comment by thepcnerdonline** [comment]
Shucks but understood. Thanks Powder.
