### ISSUE TITLE
Option to change the port.

### ISSUE THREAD

**Issue by murraydb** [DEFENDORe/pseudotv#17]
I have another service running on port 8000, so I've been editing the index.JS file manually, but a runtime parameter or at least a note on the readme might be easier.

**Comment by powdermilkman** [comment]
I will look into this for the 0.0.6 release

**Comment by Wolfie713** [comment]
There is already a parameter to change the port when executing it.  Look at the readme.md file in the Installation section.  The parameter is `--port <port#>` and has `--port 8000` used in examples.

**Comment by powdermilkman** [comment]
You are correct wolfie, Since I use docker and I can map ports there I didn’t know about the command line argument. 

Closing issue

**Comment by murraydb** [comment]
Sorry somehow missed that.
