### ISSUE TITLE
Automated Builds Issue - .exe doesn't start

### ISSUE THREAD

**Issue by lsultana98** [DEFENDORe/pseudotv#25]
Once opening the pseudotv executable is executed, it quickly flashes on and off. The service isn't started. Is there something I am missing.

**Comment by thepcnerdonline** [comment]
Same here on x64 Win

**Comment by powdermilkman** [comment]
I will try another build in the morning, might have something to do with me building it on a Mac system, I’ll try it on windows.

**Comment by thepcnerdonline** [comment]
powder ... would it be possible to have an x86 build as well for Windows or is that too much? I am running plex on 2 different architectures while live tv and dvr are free for one still.

**Comment by powdermilkman** [comment]
Yeah, when I build on windows I should be able to do x86.

**Comment by thepcnerdonline** [comment]
Excellent. Thank you.

**Comment by korumera** [comment]
Got the same issue on the moment, and an other small thingy the new download is pseudotv-win wintout the pseudotv-win-x64 :) if you make 2 versions that would be nice to include again.

**Comment by powdermilkman** [comment]
ok, windows builds are done, closing issue
