### ISSUE TITLE
Playing Original Quality

### ISSUE THREAD

**Issue by lsultana98** [DEFENDORe/pseudotv#31]
I personally don’t mind the transcoding part. However I was wondering if we could play the original resolution of the media (720p/1080p/480p). 

Right now to do this I have to use the direct stream option, which is causing some issues with devices that can’t direct stream my library. 

Is this a possibility?

**Comment by powdermilkman** [comment]
When we transcode multiple videos into a single stream we can't change the resolution of the video mid-stream.  best option is to just pick the highest common resolution and set that in the options so lower res will upscale and higher res won't loose quality.

One feature that might make it into the rebuild is per channel resolutions.
