### ISSUE TITLE
Version not displayed upon start

### ISSUE THREAD

**Issue by Wolfie713** [DEFENDORe/pseudotv#4]
Very minor issue, but a helpful one nonetheless.  Having the version number displayed upon execution (when it displays "HTTP server running on port") could help with troubleshooting, as someone could verify they are running the latest version vs only thinking they are.

Another issue I'd like to address is that Dan hasn't commented on my feature requests about making content blocks and such.  😁

**Comment by powdermilkman** [comment]
Added simple version print on load with bf60a6a35c7a4227f923d46d955db4911eb82a2f
