### ISSUE TITLE
REQ: Overcoming EPG limitation by merging external XMLTV into pseudotv

### ISSUE THREAD

**Issue by ccarpo** [DEFENDORe/pseudotv#45]
As a user with multiple Live TV input sources 
I'd like to import the channels of an external XMLTV file to pseudotv 
to be able to use multiple Live TV sources with one EPG in Plex provided by pseudotv.

* Importing the XMLTV should be possible via an URL or a local file.
* After uploading and parsing the XMLTV, I want to select out of a list of new channels which to import. 
* Bonus points for sorting and choosing the channel numbers

**Comment by ReenigneArcher** [comment]
You probably don't want to add another service, but if you use xTeVe (it's also an HD Homerun emulator). You can import the m3u and xml list from PseudoTV. You can create a filter to filter channels based on name, category, etc.

It will generate a new combined m3u and xml file.

You may want to disable the xTeVe buffer agent though as it would be buffering the file that's already buffered from PseudoTV. I did a small test with the xTeVe buffer agent and it worked well. CPU didn't go above 10%.

Not sure what your other Live TV sources are, but for me I have the following.

-OTA to NextPVR (created manual m3u from http stream addresses) to xTeVe to Plex
-IPTV to xTeVe to Plex
-PseudoTV to xTeVe to Plex

**Comment by ccarpo** [comment]
Yeah. Would have been cool to avoid xTeVe but that'll work. 
Thanks for the explanation, I'm not that familiar with xTeVe.
