### ISSUE TITLE
Add a quick "Duplicate channel" button

### ISSUE THREAD

**Issue by rspeicher** [DEFENDORe/pseudotv#74]
First, thank you for building this. It's exactly what I've been wanting since first discovering PseudoTV for XBMC (pre-Kodi) so long ago. I'm amazed that it works and can't wait to see where it goes. 👏 

I'd really appreciate a button in the web interface to quickly duplicate a channel. My current strategy is to have 2-5 channels with the same content but in different, random order since I'm never sure what I'll be in the mood for. Having a built-in way to duplicate a channel in the web interface would really speed things up.

Thanks!

**Comment by vexorian** [comment]
It could happen, but also since you would need to manually shuffle each of the copies, maybe you'd find it more convenient to use Plex playlists? Create a playlist with the contents for your channel, then create the same channel three times, each time loading the same plex playlist and shuffling.
