### ISSUE TITLE
location of the .pseudotv/xmltv.xml

### ISSUE THREAD

**Issue by siddrajput** [DEFENDORe/pseudotv#76]
I'm running Pseudotv on Windows but my Plex server is on a raspberry pi. How to I feed the location of the .pseudotv/xmltv.xml to the Plex server? This file is on the Windows PC, not on the raspberry pi.

**Comment by C-Fu** [comment]
Share the xmltv.xml folder from the Windows PC (eg. 192.168.0.10), and point your plex server's Live TV xml location to 192.168.0.10/sharedfoldername/xmltv.xml

**Comment by siddrajput** [comment]
Thanks.
