### ISSUE TITLE
Option to open a new ffmpeg log window when starting stream

### ISSUE THREAD

**Issue by FangsMcWolf** [DEFENDORe/pseudotv#8]
This comes with an added feature request.  Time stamp when forking the new window, and time stamp when it closes, so there is a log of the activity.
```
[YYYY-MM-DD HH:ii:ss] Stream started for channel (# - channel name)
[YYYY-MM-DD HH:ii:ss] Stream ended.  (Indicate if it didn't close nicely, ie, erred out.)
```

Yet another request, option to log details of last error to a file.

**Comment by powdermilkman** [comment]
Can you explain better what you mean by “fork a new window”?

**Comment by FangsMcWolf** [comment]
Pseudo window makes a new window running ffmpeg (which keeps control until window closes).

Are you not familiar with the term? 😕

**Comment by powdermilkman** [comment]
Yes i know the term, I just use the docker version of pseudotv so I wasn’t aware of it opening a new window on starting a stream.

**Comment by FangsMcWolf** [comment]
It's a requested optional feature.  But now that you mention docker, is that something possible on a docker system?  The idea here is to let the "admin" have a condensed historical output and see activity when a stream is active.

**Comment by powdermilkman** [comment]
That is currently what you see in the docker log, a single log output with all actions (start stream, end stream, ffmpeg log.)

**Comment by FangsMcWolf** [comment]
It's the same on a windows system.  I was asking if this feature would be possible on a docker system.  Hoping to not make requests that wouldn't be available in all versions.

**Comment by powdermilkman** [comment]
It wouldn’t do anything on a docker container as there is no desktop to open windows on. I think the better solution here is what I posted in #9 and has log viewable in browser while saving the log files to disk.

**Comment by powdermilkman** [comment]
Closing issue in favor of #9 solution.
