### ISSUE TITLE
Channel Logo Request

### ISSUE THREAD

**Issue by binarygeek119** [DEFENDORe/pseudotv#86]
if anyone has any request i can try to whip something up

i will add to list so i have something to work off of.

request in this form plz
channel name | Movie Or TV Show | kind of logo (text and/or icon) | include slogan (yes, no) | slogan (text to put)
|---------------|-----------------------------------|---------------------------|----------------------|----------------------
Creature Double Feature | Movie | Icon and text | no| none 
FlashBack TV | Tv Show |text and icon | no | none
Flip Television | Tv Show | text | no | nano
Hero TV | Movie | icon and test | yes | Movies 4 Heros
Retro TV | Tv Show | icon and test | no |  none
Slappy | Tv Show | icon and test | no |  none

**Comment by vexorian** [comment]
Sorry about the apathy, the issues forum is not very active.

We are going to open a repository for (not trademarked) channel assets soon, hope to see you around when that happens.
