### ISSUE TITLE
xmltv.xml File is empty

### ISSUE THREAD

**Issue by pedwards3x** [DEFENDORe/pseudotv#87]
I have this up and running on my Plex server and everything is working well, except the xmltv.xml file only contains the following after it is updated:

`<?`

There are no issues writing to the file, and the stream will work, but the guide in Plex is not working due to no data being created in the xmltv.xml file. Any advice?

**Comment by vexorian** [comment]
This sounds really strange, what version are you using? Do you have really big channels? What's the size of your channels.json ?

**Comment by pedwards3x** [comment]
I just cloned the default branch 4 days ago. Channel size does not seem to matter, I have tried creating a large channel and a small channel with 5 episodes of a show on it, same result. I just looked and channels.json is 14K in size.

<img width="425" alt="2020-07-27 13_39_05-maverick@mavplex_ ~_pseudotv_ pseudotv" src="https://user-images.githubusercontent.com/2141190/88573393-a683da80-d00e-11ea-8a1d-0cd01cd2112a.png">

**Comment by mchal** [comment]
src/xmltv.js
Line 35 - should be `ws.end();` and not `ws.close();`

**Comment by vexorian** [comment]
cool find. This should explain many random xmltv issues

**Comment by pedwards3x** [comment]
Yup, this fixed everything for me. Thanks!
