### ISSUE TITLE
English Audio

### ISSUE THREAD

**Issue by clrksml** [DEFENDORe/pseudotv#88]
Trying to get it to output english audio. Have some shows that have dual audio. 

Tried to do it myself but clearly didn't work.

**Comment by vexorian** [comment]
What version are you using? I have dual audio videos and they work fine. In one of the versions, you had to pick the audio for each program (clicking the program in the channel's window). In the latest dev version, it plays the same audio configured in Plex for the user configured for pseudotv.

**Comment by clrksml** [comment]
That's the issue. I pulled from Community Plugins on unraid and it's using latest version.
